import httpx
from app.supabase_client import get_supabase
from app.config import get_settings
from app.schemas import (
    ExtractTermsRequest,
    ExtractTermsResponse,
    ExtractedTerms,
    SendSigningLinksRequest,
    SendSigningLinksResponse,
    ClientSigningInfo,
)

settings = get_settings()
supabase = get_supabase()


# Contracts

def create_contract(owner_id: str, data: dict) -> dict:
    """
    Inserts a new contract row in draft status.
    Reference number is auto-generated by the DB trigger.
    """
    response = (
        supabase.table("contracts")
        .insert({
            "owner_id": owner_id,
            "title": data.get("title"),
            "raw_input": data.get("raw_input"),
            "input_type": data.get("input_type", "paste"),
            "screenshot_url": data.get("screenshot_url"),
            "escrow_proposed": data.get("escrow_proposed", False),
            "escrow_proposed_by": data.get("escrow_proposed_by"),
            "status": "draft",
        })
        .execute()
    )
    return response.data[0]


def get_contract(contract_id: str) -> dict | None:
    response = (
        supabase.table("contracts")
        .select("*")
        .eq("id", contract_id)
        .single()
        .execute()
    )
    return response.data


def get_contracts_by_owner(owner_id: str) -> list[dict]:
    response = (
        supabase.table("contracts")
        .select("*")
        .eq("owner_id", owner_id)
        .order("created_at", desc=True)
        .execute()
    )
    return response.data


def update_contract(contract_id: str, data: dict) -> dict:
    response = (
        supabase.table("contracts")
        .update(data)
        .eq("id", contract_id)
        .execute()
    )
    return response.data[0]


# Term extraction

async def extract_terms(request: ExtractTermsRequest) -> ExtractTermsResponse:
    """
    Calls the extract-terms Supabase edge function, then writes the
    result back to contracts.extracted_terms and the denormalised columns.
    """
    edge_url = f"{settings.supabase_url}/functions/v1/extract-terms"

    payload = {
        "text": request.text,
        "image_url": request.image_url,
        "input_type": request.input_type,
    }

    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            edge_url,
            json=payload,
            headers={
                "Authorization": f"Bearer {settings.supabase_service_role_key}",
                "Content-Type": "application/json",
            },
        )

    if response.status_code != 200:
        raise Exception(f"extract-terms edge function error: {response.text}")

    result = response.json()
    terms = result["extracted_terms"]

    # Write extracted terms back to Supabase —
    # both the raw blob and the denormalised columns for querying
    supabase.table("contracts").update({
        "extracted_terms": terms,
        "service_provider": terms.get("service_provider"),
        "client": terms.get("client"),
        "deliverables": terms.get("deliverables"),
        "payment": terms.get("payment"),
        "timeline": terms.get("timeline"),
        "default_clause": terms.get("default_clause"),
        "ambiguities": terms.get("ambiguities"),
    }).eq("id", request.contract_id).execute()

    # Log the event
    supabase.table("contract_events").insert({
        "contract_id": request.contract_id,
        "actor_role": "system",
        "event_type": "terms_extracted",
        "metadata": {
            "input_type": request.input_type,
            "ambiguity_count": len(terms.get("ambiguities", [])),
        },
    }).execute()

    return ExtractTermsResponse(
        contract_id=request.contract_id,
        extracted_terms=ExtractedTerms(**terms),
    )


# Signing links

async def send_signing_links(request: SendSigningLinksRequest) -> SendSigningLinksResponse:
    """
    Calls the send-signing-links Supabase edge function.
    Updates the contract status to pending_signatures beforehand.
    """
    # Move contract to pending_signatures before sending links
    supabase.table("contracts").update({
        "status": "pending_signatures",
    }).eq("id", request.contract_id).execute()

    edge_url = f"{settings.supabase_url}/functions/v1/send-signing-links"

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            edge_url,
            json={"contract_id": request.contract_id},
            headers={
                "Authorization": f"Bearer {settings.supabase_service_role_key}",
                "Content-Type": "application/json",
            },
        )

    if response.status_code != 200:
        # Roll back status if the edge function failed
        supabase.table("contracts").update({
            "status": "draft",
        }).eq("id", request.contract_id).execute()
        raise Exception(f"send-signing-links edge function error: {response.text}")

    result = response.json()

    return SendSigningLinksResponse(
        success=True,
        client=ClientSigningInfo(**result["client"]),
        service_provider=result["service_provider"],
    )


# Milestones

def create_milestone(data: dict) -> dict:
    response = (
        supabase.table("milestones")
        .insert(data)
        .execute()
    )
    return response.data[0]


def get_milestones(contract_id: str) -> list[dict]:
    response = (
        supabase.table("milestones")
        .select("*")
        .eq("contract_id", contract_id)
        .order("position")
        .execute()
    )
    return response.data


# Escrow conditions

def create_escrow_condition(data: dict) -> dict:
    response = (
        supabase.table("escrow_conditions")
        .insert(data)
        .execute()
    )
    return response.data[0]


def get_escrow_conditions(contract_id: str) -> list[dict]:
    response = (
        supabase.table("escrow_conditions")
        .select("*")
        .eq("contract_id", contract_id)
        .order("position")
        .execute()
    )
    return response.data