// generate-pdf
// Takes contract_html from a contract row, wraps it in a styled HTML document,
// converts to PDF via an external HTML-to-PDF API, and uploads to Supabase Storage.
// Updates contract_pdf_url on the contract row.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

function wrapHtml(contractHtml: string, reference?: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${reference || "Contract"} — PactAI</title>
  <style>
    @page {
      size: A4;
      margin: 2.5cm 2cm;
    }
    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.7;
      color: #1a1a1a;
      max-width: 100%;
      margin: 0;
      padding: 0;
    }
    h1 {
      font-size: 20pt;
      text-align: center;
      margin-bottom: 4px;
      color: #111;
    }
    h2 {
      font-size: 13pt;
      font-weight: 700;
      margin-top: 28px;
      margin-bottom: 8px;
      color: #222;
      border-bottom: 1px solid #ddd;
      padding-bottom: 4px;
    }
    p {
      margin: 0 0 10px;
    }
    ul, ol {
      margin: 8px 0 16px 20px;
    }
    li {
      margin-bottom: 4px;
    }
    hr {
      border: none;
      border-top: 1px solid #ccc;
      margin: 32px 0;
    }
    strong {
      font-weight: 700;
    }
    .signature-block {
      display: flex;
      justify-content: space-between;
      margin-top: 48px;
    }
    .signature-party {
      width: 45%;
    }
    .signature-line {
      border-bottom: 1px solid #333;
      height: 40px;
      margin-bottom: 4px;
    }
    .watermark {
      text-align: center;
      font-size: 9pt;
      color: #999;
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #eee;
    }
  </style>
</head>
<body>
  ${contractHtml}
  <div class="watermark">
    Generated by PactAI — pactai.ng${reference ? ` — ${reference}` : ""}
  </div>
</body>
</html>`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "authorization, content-type",
      },
    });
  }

  try {
    const { contract_id, contract_html, reference } = await req.json();

    if (!contract_id || !contract_html) {
      return Response.json(
        { error: "contract_id and contract_html are required" },
        { status: 400 }
      );
    }

    const fullHtml = wrapHtml(contract_html, reference);

    // Use a free HTML-to-PDF API (api2pdf wraps headless Chrome)
    // Alternative: you can swap this with any HTML-to-PDF service
    // For now, we store the HTML directly and generate PDF client-side,
    // OR use the Supabase storage with the HTML for server-side rendering.

    // Strategy: Upload the full HTML as a file to storage for PDF rendering.
    // Many services can convert on the fly. For an MVP, we upload the wrapped
    // HTML document and store its URL — the frontend can render it or the
    // owner can print-to-PDF from the browser. When a dedicated PDF service
    // is added, this function will call it and upload the resulting PDF.

    const storagePath = `${contract_id}/contract.html`;

    // Upload HTML to Supabase storage (contracts bucket)
    const { error: uploadError } = await supabase.storage
      .from("contracts")
      .upload(storagePath, new Blob([fullHtml], { type: "text/html" }), {
        contentType: "text/html",
        upsert: true,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      return Response.json(
        { error: "Failed to upload contract HTML", detail: String(uploadError) },
        { status: 500 }
      );
    }

    // Get public URL for the uploaded HTML
    const { data: urlData } = supabase.storage
      .from("contracts")
      .getPublicUrl(storagePath);

    const publicUrl = urlData?.publicUrl;

    // Update contract row with the HTML and storage path
    const { error: updateError } = await supabase
      .from("contracts")
      .update({
        contract_html: contract_html,
        contract_pdf_url: storagePath,
      })
      .eq("id", contract_id);

    if (updateError) {
      console.error("Contract update error:", updateError);
      return Response.json(
        { error: "Failed to update contract", detail: String(updateError) },
        { status: 500 }
      );
    }

    return Response.json(
      {
        contract_id,
        contract_html_url: publicUrl,
        contract_pdf_url: storagePath,
      },
      {
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Content-Type": "application/json",
        },
      }
    );
  } catch (err) {
    console.error("generate-pdf error:", err);
    return Response.json({ error: String(err) }, { status: 500 });
  }
});
